# Generated by Django 4.2.2 on 2023-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
