# Generated by Django 4.2.2 on 2023-08-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_task_assigned_taskassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
